## Heating

```{r heatingtimes}

if (heating_times == 'NA') {
  # step find heating_times
  dts <- heating_time(dts,
                      heating_type = 'both')
} else {
  dts <- set_values_for_time(dts, 
                             variable_name = 'type', 
                             begin = heating_distance[1], 
                             end = heating_distance[2],
                             set_to = 'heating')
}

s_t <- min(get_time_table(dts)[type == 'heating']$start)
e_t <- max(get_time_table(dts)[type == 'heating']$start)
```


```{r heatingdistance}

if (heating_distance == 'NA') {
  # step find heating_distances
  dts <- heating_distance(dts,
                          heating_type = 'heating')
} else {
  dts <- set_values_for_distance(dts,
                                 variable_name = 'heated',
                                 begin = heating_distance[1], 
                                 end = heating_distance[2])
}
s_d <- min(get_distance_table(dts)[heated == TRUE]$distance)
e_d <- max(get_distance_table(dts)[heated == TRUE]$distance)
```

Heating was performed from `r s_t` to `r e_t` at a power output of `r heating_power`.  The heating distances are from `r s_d` to `r e_d`

