## Water bath diagnostic

```{r waterbath}

print(class(bath_location))
if (bath_location == 'NA') {
  print(class(bath_location))
  # dts <- set_values_for_distance(dts, 
  #                         variable_name = 'bath',
  #                         begin = bath_location[1],
  #                         end = bath_location[2])
} else {
  # step find water bath
  dts <- find_water_bath(dts, buffer = 0.1)
}

dts <- bath_calibration(dts, smooth = TRUE)

```

```{r bathlocation}

ggplot(get_distance_table(dts), aes(x = distance, y = as.numeric(bath))) + 
  geom_line() + theme_bw()

```

```{r temperatures}

trace_time <- melt(get_time_table(dts), id.vars = 'start')
trace_time_sub <- trace_time[variable %in% 
                               c('probe_1', 
                                 'probe_2',
                                 'calib_temperature')]

ggplot(trace_time_sub, aes(x = start, y = value, color = variable, group = variable)) +
  geom_line()  + 
  xlab('') + 
  ylab('Temperature 째C') + 
  scale_x_continuous(expand = c(0, 0)) + 
  ggtitle('Water bath probe temperatures a smoothed average for calibration') + theme_bw()

```

```{r dtsbathtemperature}

dts_bath <- subset_distance(dts, by = 'bath')
trace_time <- dts::sample_distance(dts_bath, n_traces = 10)
trace_time[, start := as.POSIXct(as.numeric(start), origin = '1970-01-01')]

ggplot(trace_time, aes(x = start, y = temperature, group = distance, color = as.factor(distance))) +
  geom_line() + 
  scale_color_viridis_d(alpha = 0.2) + 
  xlab('') + 
  ylab('Temperature 째C') + 
  scale_x_continuous(expand = c(0, 0)) + 
  ggtitle('Uncalibrated water bath temperatures from DTS along fiber optic cable')  + theme_bw() + 
  theme(legend.position = 'none')

```


```{r reftemperatures}

trace_time <- melt(get_time_table(dts), id.vars = 'start')
trace_time_sub <- trace_time[variable == 'reference_temperature']

ggplot(trace_time_sub, aes(x = start, y = value)) +
  geom_line() + 
  xlab('') + 
  ylab('Temperature 째C') + 
  scale_x_continuous(expand = c(0, 0)) + 
  ggtitle('Reference temperature during test') + theme_bw()

```


```{r calibrationadjust}

trace_time <- get_time_table(dts)[, list(start, calib_temperature_raw, calib_temperature, bath_temperature_dts, reference_temperature, calib_adj)]
trace_time <- melt(trace_time, id.vars = 'start')
trace_time[, start := as.POSIXct(start, origin = '1970-01-01')]
ggplot(trace_time, aes(x = start, y = value)) +
  geom_line() + 
  xlab('') + 
  ylab('Temperature Adjustment 째C') + 
  scale_x_continuous(expand = c(0, 0)) + 
  facet_wrap(variable~., ncol = 1, scales = 'free_y') + 
  ggtitle('Temperature shift for calibration') + 
  theme_bw()

```