# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title read file fast
#' 
#' 
#' @param path
#' 
#' @examples
#' 
#' @export
read_file_cpp <- function(path) {
    .Call(`_dts_read_file_cpp`, path)
}

#' @title correlation for dts matrix by row or by column
#' 
#' 
#' @param x
#' @param dim
#' 
#' @examples
#' 
#' @export
cor_by_trace <- function(x, dim) {
    .Call(`_dts_cor_by_trace`, x, dim)
}

#' @title correlation for dts matrix by row or by column
#' 
#' 
#' @param x
#' @param y
#' @param dim
#' 
#' @examples
#' 
#' @export
cor_with_trace <- function(x, y, dim) {
    .Call(`_dts_cor_with_trace`, x, y, dim)
}

#' @title prediction for dts matrix by row or by column
#' 
#' 
#' @param x
#' @param y
#' @param dim
#' 
#' @examples
#' 
#' @export
residual_variance_with_trace <- function(x, y, dim) {
    .Call(`_dts_residual_variance_with_trace`, x, y, dim)
}

#' @title Difference between dts matrix by row or by column
#' 
#' 
#' @param x matrix
#' @param shift how many values to shift
#' @param dim by row or by column
#' 
#' @examples
#' 
#' @export
diff_by_trace <- function(x, shift, dim) {
    .Call(`_dts_diff_by_trace`, x, shift, dim)
}

#' @title solve_arma
#' 
#' 
#' @param x matrix
#' @param y vector
#' 
#' @examples
#' 
#' @export
solve_arma <- function(x, y) {
    .Call(`_dts_solve_arma`, x, y)
}

