# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title read file fast
#' 
#' 
#' @param path
#' 
#' @examples
#' 
#' @export
read_file_cpp <- function(path) {
    .Call(`_dts_read_file_cpp`, path)
}

#' @title correlation for dts matrix by row or by column
#' 
#' 
#' @param x
#' @param dim if 0 then it is by column
#' 
#' @examples
#' 
#' @export
cor_by_trace <- function(x, dim) {
    .Call(`_dts_cor_by_trace`, x, dim)
}

#' @title correlation for dts matrix by row or by column
#' 
#' 
#' @param x
#' @param y
#' @param dim
#' 
#' @examples
#' 
#' @export
cor_with_trace <- function(x, y, dim) {
    .Call(`_dts_cor_with_trace`, x, y, dim)
}

#' @title prediction for dts matrix by row or by column
#' 
#' 
#' @param x
#' @param y
#' @param dim
#' 
#' @examples
#' 
#' @export
residual_variance_with_trace <- function(x, y, dim) {
    .Call(`_dts_residual_variance_with_trace`, x, y, dim)
}

#' @title Difference between dts matrix by row or by column
#' 
#' 
#' @param x matrix
#' @param shift how many values to shift
#' @param dim by row or by column
#' 
#' @examples
#' 
#' @export
diff_by_trace <- function(x, shift, dim) {
    .Call(`_dts_diff_by_trace`, x, shift, dim)
}

#' @title solve_arma
#' 
#' 
#' @param x matrix
#' @param y vector
#' 
#' @examples
#' 
#' @export
solve_arma <- function(x, y) {
    .Call(`_dts_solve_arma`, x, y)
}

#' @title rolling_diff
#' 
#' 
#' @param x matrix
#' @param y integer vector
#' 
#' @examples
#' 
#' @export
rolling_diff <- function(x, inds) {
    .Call(`_dts_rolling_diff`, x, inds)
}

#' @title refine_match
#' 
#' 
#' @param x matrix
#' @param y vector
#' 
#' @examples
#' 
#' @export
refine_match <- function(x, y, resolution_sub = 0.01) {
    .Call(`_dts_refine_match`, x, y, resolution_sub)
}

